ckanext/charts/chart_builders/__init__.py
from __future__ import annotations

from .base import BaseChartBuilder
from .chartjs import ChartJSBarBuilder
from .echarts import EChartsBuilder
from .observable import ObservableBuilder
from .plotly import PlotlyBuilder
from .plotly.bar import PlotlyBarForm

DEFAULT_CHART_FORM = PlotlyBarForm


def get_chart_engines() -> dict[str, type[BaseChartBuilder]]:
    return {
        "plotly": PlotlyBuilder,
        "observable": ObservableBuilder,
        "chartjs": ChartJSBarBuilder,
        "echarts": EChartsBuilder,
    }

ckanext/charts/chart_builders/echarts/__init__.py
from __future__ import annotations

from .bar import EChartsBuilder  # noqa

ckanext/charts/chart_builders/plotly/__init__.py
from __future__ import annotations

from .base import PlotlyBuilder  # noqa

ckanext/charts/views.py
from __future__ import annotations

from flask import Blueprint, jsonify
from flask.views import MethodView

import ckan.plugins.toolkit as tk
from ckan.logic import parse_params
from ckan.plugins import plugin_loaded

from ckanext.charts import cache, exception, fetchers, utils

charts = Blueprint("charts_view", __name__)
ERROR_TEMPLATE = "charts/snippets/error_chart.html"


@charts.route("/api/utils/charts/<resource_id>/update-chart")
def update_chart(
    resource_id: str,
) -> str:  # noqa: PLR0911
    """Update chart.

    This will be called from the resource view to update the chart.

    Args:
        resource_id (str): The resource id
    """
    data = parse_params(tk.request.args)

    resource_view_id = data.get("resource_view_id")

    try:
        builder = _get_form_builder(data)  # type: ignore
    except exception.ChartTypeNotImplementedError:
        return tk.render(ERROR_TEMPLATE)

    try:
        data, errors = tk.navl_validate(data, builder.get_validation_schema(), {})
    except exception.ChartBuildError as e:
        return tk.render(
            ERROR_TEMPLATE,
            {"error_msg": tk._(f"Error building chart: {e}")},
        )

    if errors:
        return tk.render_snippet(ERROR_TEMPLATE, {"error_msg": errors})

    try:
        return tk.render_snippet(
            f"charts/snippets/{data['engine']}_chart.html",
            {
                "chart": utils.build_chart_for_resource(
                    data,
                    resource_id,
                    resource_view_id,  # type: ignore
                ),
            },
        )
    except exception.ChartTypeNotImplementedError:
        return tk.render(ERROR_TEMPLATE)
    except exception.ChartBuildError as e:
        return tk.render(
            ERROR_TEMPLATE,
            {"error_msg": tk._(f"Error building chart: {e}")},
        )
    # TODO: we probably want to know which exceptions exactly could happen instead
    except Exception as e:  # noqa
        return tk.render(
            ERROR_TEMPLATE,
            {"error_msg": tk._(f"Error building chart: {e}")},
        )


@charts.route("/api/utils/charts/update-form")
def update_form():
    data = parse_params(tk.request.args)
    resource_id = data["resource_id"]
    user_builder: bool = tk.asbool(data.pop("user_chart_builder", False))

    # if we're changing the engine, drop the chart type, cause we don't know
    # the list of supported types for the new engine
    if data.pop("reset_engine", False):
        data["type"] = ""

    try:
        builder = _get_form_builder(data)
    except exception.ChartTypeNotImplementedError:
        return tk.render(ERROR_TEMPLATE)

    try:
        data, errors = tk.navl_validate(data, builder.get_validation_schema(), {})
    except exception.ChartBuildError as e:
        return tk.render(
            ERROR_TEMPLATE,
            {"error_msg": tk._(f"Error building chart: {e}")},
        )

    extra_vars = {
        "builder": builder,
        "resource_id": resource_id,
        "data": data,
        "errors": errors,
        "active_tab": "Structure",
        "user_chart_builder": user_builder,
    }

    if user_builder:
        extra_vars["exclude_tabs"] = ["General"]

    return tk.render_snippet("charts/snippets/charts_form_fields.html", extra_vars)


@charts.route("/api/utils/charts/<resource_id>/clear-chart")
def clear_chart(resource_id: str):
    return _clear_chart(resource_id)


@charts.route("/api/utils/charts/<resource_id>/clear-builder-chart")
def clear_user_builder_chart(resource_id: str):
    return _clear_chart(resource_id, exclude_tabs=["General"], user_chart_builder=True)


def _clear_chart(
    resource_id: str,
    exclude_tabs: None | list[str] = None,
    user_chart_builder: bool = False,
):
    builder = _get_form_builder(
        {"engine": "plotly", "type": "Bar", "resource_id": resource_id},
    )

    data, errors = tk.navl_validate({}, builder.get_validation_schema(), {})

    if not exclude_tabs:
        exclude_tabs = []

    return tk.render_snippet(
        "charts/snippets/charts_form_fields.html",
        {
            "builder": builder,
            "resource_id": resource_id,
            "data": data,
            "errors": errors,
            "active_tab": "General",
            "exclude_tabs": exclude_tabs,
            "user_chart_builder": user_chart_builder,
        },
    )


def _get_form_builder(data: dict[str, str]):
    """Get form builder for the given engine and chart type"""
    if "engine" not in data or "type" not in data:
        raise exception.ChartTypeNotImplementedError

    builder = utils.get_chart_form_builder(data["engine"], data["type"])

    return builder(data["resource_id"], data.get("resource_view_id"), settings=data)


@charts.route("/api/utils/charts/get-values")
def get_chart_column_values():
    data = parse_params(tk.request.args)

    resource_id = tk.get_or_bust(data, "resource_id")
    column = tk.get_or_bust(data, "column")

    fetcher = fetchers.DatastoreDataFetcher(resource_id, settings=data)

    result = []

    for val in fetcher.fetch_data()[column].tolist():
        if val in result:
            continue

        result.append(val)

    return jsonify(sorted(result))


if plugin_loaded("admin_panel"):
    from ckanext.ap_main.utils import ap_before_request
    from ckanext.ap_main.views.generics import ApConfigurationPageView

    charts_admin = Blueprint("charts_view_admin", __name__)
    charts_admin.before_request(ap_before_request)

    class ConfigClearCacheView(MethodView):
        def post(self):
            if "invalidate-all-cache" in tk.request.form:
                cache.invalidate_all_cache()

            if "invalidate-redis-cache" in tk.request.form:
                cache.drop_redis_cache()

            if "invalidate-file-cache" in tk.request.form:
                cache.drop_file_cache()

            tk.h.flash_success(tk._("Cache has been cleared"))

            return tk.h.redirect_to("charts_view_admin.config")

    charts_admin.add_url_rule(
        "/admin-panel/charts/clear-cache",
        view_func=ConfigClearCacheView.as_view("clear_cache"),
    )
    charts_admin.add_url_rule(
        "/admin-panel/charts/config",
        view_func=ApConfigurationPageView.as_view(
            "config",
            "charts_config",
            render_template="charts/config.html",
            page_title=tk._("Charts config"),
        ),
    )

ckanext/charts/templates/charts/charts_builder_form.html
{% import 'macros/form.html' as form %}

{% set data = data or {} %}
{% set errors = errors or {} %}

{{ form.errors(error_summary) }}

{{ form.input('title', id='field-title', label=_('Title'), placeholder=_('eg. My View'), value=data.title, error=errors.title, classes=['control-full', 'control-large'], is_required=true) }}
{{ form.markdown('description', id='field-description', label=_('Description'), placeholder=_('eg. Information about my view'), value=data.description, error=errors.description) }}

ckanext/charts/templates/charts/charts_builder_view.html
{% if not h.charts_user_is_authenticated() and not h.charts_allow_anon_building_charts() %}
    {{ _("You have to login to access the chart builder.") }}
    <a href="{{ h.url_for('user.login', came_from=request.full_path) }}">{{ _("Click here to login") }}</a>
{% else %}
    <form method="POST">
        {% snippet "charts/snippets/chart_create_form.html",
            resource_id=resource_id,
            resource_view_id=resource_view_id,
            settings=settings,
            form_builder=form_builder(resource_id=resource_id, resource_view_id=resource_view_id, settings=settings),
            errors={},
            exclude_tabs=["General"],
            user_chart_builder=true
        %}
    </form>
{% endif %}

ckanext/charts/templates/charts/charts_form.html
{% snippet "charts/snippets/chart_create_form.html",
    resource_id=resource_id,
    resource_view_id=resource_view_id,
    settings=settings,
    form_builder=form_builder(resource_id, resource_view_id=resource_view_id, settings=settings),
    errors=errors
%}

ckanext/charts/templates/charts/charts_view.html
{% include ["charts/snippets/" ~ settings.engine ~ "_chart.html", "charts/snippets/error_chart.html"] %}

ckanext/charts/templates/charts/config.html
{% extends 'admin_panel/config/autogenerated_config.html' %}

{% block before_form %}
    <form method="POST" action="{{ h.url_for('charts_view_admin.clear_cache') }}" class="mb-3">
        <button type="submit" name="invalidate-all-cache" value="clear_cache" class="btn btn-primary">
            </i>{{ _('Invalidate ALL cache') }}
        </button>

        <button type="submit" name="invalidate-redis-cache" value="clear_cache" class="btn btn-primary">
            </i>{{ _('Invalidate Redis cache') }}
        </button>

        <button type="submit" name="invalidate-file-cache" value="clear_cache" class="btn btn-primary">
            </i>{{ _('Invalidate File cache') }}
        </button>
    </form>

    <p><b>{{ _("Redis cache size") }}: <span><i>{{ h.get_redis_cache_size() }}</i></span></b></p>
    <p><b>{{ _("File cache size") }}: <span><i>{{ h.get_file_cache_size() }}</i></span></b></p>
{% endblock %}

ckanext/charts/templates/charts/snippets/chart_create_form.html
{% import "macros/form.html" as form %}

{% asset "charts/plotly" %}
{% asset "charts/chartjs" %}
{% asset "charts/observable" %}
{% asset "charts/echarts" %}

{# Global styles for all charts #}
{% asset "charts/charts-css" %}
{% asset "charts/charts-js" %}

{# Custom select library #}
{% asset "charts/tom-select-js" %}
{% asset "charts/tom-select-css" %}

{# chart form #}
<div class="charts-view--form" data-module="charts-global" data-module-reinit-js="{{ h.charts_reinit_ckan_js_modules() }}">
    {% snippet "charts/snippets/charts_form_fields.html",
        resource_id=resource_id,
        resource_view_id=resource_view_id,
        data=settings,
        builder=form_builder,
        errors=errors,
        exclude_tabs=exclude_tabs or false,
        user_chart_builder=user_chart_builder or false
    %}
</div>

{# a spinner to show when the chart is updating #}
<div id="chart-indicator">
    {% snippet "charts/snippets/svg/loader.svg" %}
    {{ _("Updating chart...") }}
</div>

{# a container for the chart preview #}
<div class="charts-view--preview" id="charts-view--preview" style="min-height: 450px;">

</div>

ckanext/charts/templates/charts/snippets/chartjs_chart.html
{% asset "charts/chartjs" %}

{% if chart %}
    <canvas
        id="chart-container--{{ h.charts_generate_unique_id() }}"
        class="chart-container"
        data-module="charts-render-chartjs"
        data-module-config="{{ chart }}">
    </canvas>

    <div class="chart-control mt-2">
        <button class="btn btn-primary" id="resetZoom" title="{{ _('Reset') }}">
            <i class="fa fa-home"></i>
        </button>

        <button class="btn btn-primary" id="toggleZoom" title="{{ _('Toggle Zoom') }}">
            <i class="fa fa-search-plus"></i>
        </button>

        <button class="btn btn-primary" id="togglePan" title="{{ _('Toggle Pan') }}">
            <i class="fa fa-arrows"></i>
        </button>

        <a class="btn btn-primary" id="makeSnapshot" title="{{ _('Make Snapshot') }}">
            <i class="fa fa-camera"></i>
        </a>
    </div>
{% else %}
    <p class="text-muted">
        {{ _("Cannot build chart with current settings") }}
    </p>
{% endif %}

ckanext/charts/templates/charts/snippets/charts_form_field.html
{#- master snippet for all charts form fields -#}

{%- set form_snippet = field.form_snippet|default('repeating_subfields.html' if field.repeating_subfields else 'text.html') -%}

{%- if '/' not in form_snippet -%}
    {%- set form_snippet = 'scheming/form_snippets/' + form_snippet -%}
{%- endif -%}

{%- snippet form_snippet,
    field=field,
    data=data,
    errors=errors,
    resource_id=resource_id
-%}

ckanext/charts/templates/charts/snippets/charts_form_fields.html
<div class="charts-view--form">
    {% set active_tab = active_tab or "General" %}
    {% set form_tabs = builder.get_form_tabs(exclude_tabs=exclude_tabs) %}

    {% if "General" not in form_tabs %}
        {% set active_tab = form_tabs[0] %}
    {% endif %}

    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        {% for tab in form_tabs %}
            {% set tab_fields = builder.get_fields_by_tab(tab) %}
            {% if tab_fields %}
                <li class="nav-item" role="presentation">
                    <button class="nav-link {{ 'active' if tab == active_tab }}" id="pills-{{ tab }}-tab" data-bs-toggle="pill"
                        data-bs-target="#pills-{{ tab }}" type="button" role="tab" aria-controls="pills-{{ tab }}" {% if
                        tab==active_tab %}aria-selected="true" {% endif %}>{{ tab }}</button>
                </li>
            {% endif %}
        {% endfor %}

        <button class="btn btn-default" id="chart-clear" type="button"
            {% if user_chart_builder %}
                hx-get="{{ h.url_for('charts_view.clear_user_builder_chart', resource_id=resource_id) }}"
            {% else %}
                hx-get="{{ h.url_for('charts_view.clear_chart', resource_id=resource_id) }}"
            {% endif %}
            hx-trigger="click"
            hx-include="closest form" hx-target=".charts-view--form" hx-swap="outerHTML">
            {{ _("Clear") }}
        </button>
    </ul>

    <div class="tab-content active" id="pills-tabContent"
        hx-get="{{ h.url_for('charts_view.update_chart', resource_id=resource_id, resource_view_id=resource_view_id) }}" hx-trigger="load, submit, change"
        hx-include="closest form" hx-target="#charts-view--preview" hx-indicator="#chart-indicator">

        {% for tab in form_tabs %}
            {% set tab_fields = builder.get_fields_by_tab(tab) %}

            {% if tab_fields %}
                <div class="tab-pane fade {{ 'show active' if tab == active_tab }}" id="pills-{{ tab }}" role="tabpanel"
                    aria-labelledby="pills-{{ tab }}-tab">
                    {% snippet 'charts/snippets/render_fields.html',
                        fields=builder.get_fields_by_tab(tab),
                        data=data,
                        errors=errors,
                        resource_id=resource_id
                    %}
                </div>
            {% endif %}
        {% endfor %}
    </div>

    {% if user_chart_builder %}
        <input type="hidden" name="user_chart_builder" value="1">
    {% endif %}

    <input type="hidden" name="resource_id" value="{{ resource_id }}">
    <input type="hidden" name="{{ g.csrf_field_name }}" value="{{ csrf_token() }}"
        hx-swap-oob='outerHTML:[name="{{ g.csrf_field_name }}"]' />
</div>

ckanext/charts/templates/charts/snippets/echarts_chart.html
{% asset "charts/echarts" %}

{% if chart %}
    <div
        id="chart-container"
        data-module="charts-render-echarts"
        data-module-config="{{ chart }}"
        style="width: 100%;height:600px;"></div>
{% else %}
    <p class="text-muted">
        {{ _("Cannot build chart with current settings") }}
    </p>
{% endif %}

ckanext/charts/templates/charts/snippets/error_chart.html
<p class="text-muted">
    {{ error_msg or _("This chart type is not supported") }}
</p>

ckanext/charts/templates/charts/snippets/observable_chart.html
{% asset "charts/observable" %}

{% if chart %}
    <div
        id="chart-container--{{ h.charts_generate_unique_id() }}"
        class="chart-container"
        data-module="charts-render-observable"
        data-module-config="{{ chart }}">
    </div>

    <div class="chart-control mt-2">
        <a class="btn btn-primary" id="makeSnapshot" title="{{ _('Make Snapshot') }}">
            <i class="fa fa-camera"></i>
        </a>
    </div>
{% else %}
    <p class="text-muted">
        {{ _("Cannot build chart with current settings") }}
    </p>
{% endif %}

ckanext/charts/templates/charts/snippets/plotly_chart.html
{% asset "charts/plotly" %}

{% if chart %}
    <div
        id="chart-container--{{ h.charts_generate_unique_id() }}"
        class="chart-container"
        data-module="charts-render-plotly"
        data-module-config="{{ chart }}">
    </div>

    <div class="chart-control mt-2">
        <a class="btn btn-primary" id="makeSnapshot" title="{{ _('Make Snapshot') }}">
            <i class="fa fa-camera"></i>
        </a>
    </div>
{% else %}
    <p class="text-muted">
        {{ _("Cannot build chart with current settings") }}
    </p>
{% endif %}

ckanext/charts/templates/charts/snippets/render_fields.html
{% for field in fields if field.form_snippet is not none %}
    {% snippet 'charts/snippets/charts_form_field.html', field=field, data=data, errors=errors, resource_id=resource_id %}
{% endfor %}

ckanext/charts/templates/charts/snippets/unknown_form.html
<p class="text-muted">
    {{ _("Missing a form for a chart type") }}
</p>

ckanext/charts/templates/package/edit_view.html
{% ckan_extends %}

{% block wrapper_class %} {% if resource_view.view_type == 'charts_view' %}charts-view{% endif %} {{ super() }}{% endblock %}

{% block form %}
    <form class="dataset-form dataset-resource-form" method="post" data-module="basic-form resource-form">
        {{ h.csrf_input() }}
        {% include 'package/snippets/view_form.html' %}

        {# removing preview button #}
        <div class="form-actions">
            <button class="btn btn-danger pull-left" name="delete" value="Delete"> {{ _('Delete') }} </button>
            <button class="btn btn-primary" name="save" value="Save" type="submit">{{ _('Update') }}</button>
        </div>
    </form>
{% endblock %}

ckanext/charts/templates/package/new_view.html
{% ckan_extends %}

{% block wrapper_class %} {% if resource_view.view_type == 'charts_view' %} charts-view {% endif %} {{ super() }} {% endblock %}

ckanext/charts/templates/package/snippets/resource_view.html
{# alter: adding resource-view-{{ resource_view.view_type }} #}

{% import 'macros/form.html' as form %}

{% block resource_view %}
  <div id="view-{{ resource_view['id'] }}" class="resource-view resource-view-{{ resource_view.view_type }}" data-id="{{ resource_view['id'] }}" data-title="{{ resource_view['title'] }}" data-description="{{ resource_view['descripion'] }}">
  <div class="actions">
    <a class="btn btn-default"
       target="_blank"
       rel="noreferrer"
       href="{{ h.url_for(package['type'] ~ '_resource.view', id=package['name'], resource_id=resource['id'], view_id=resource_view['id'], qualified=True) }}">
      <i class="fa fa-arrows-alt"></i>
      {{ _("Fullscreen") }}
    </a>
    <a class="btn btn-default"
       href="#embed-{{ resource_view['id'] }}"
       data-module="resource-view-embed"
       data-module-id="{{ resource_view['id'] }}"
       data-module-url="{{ h.url_for(package['type'] ~ '_resource.view', id=package['name'], resource_id=resource['id'], view_id=resource_view['id'], qualified=True) }}">
      <i class="fa fa-object-group"></i>
      {{ _("Embed") }}
    </a>
  </div>
  <p class="desc">{{ h.render_markdown(resource_view['description']) }}</p>
    <div class="m-top ckanext-datapreview">
      {% if not to_preview and h.resource_view_is_filterable(resource_view) %}
        {% snippet 'package/snippets/resource_view_filters.html', resource=resource %}
      {% endif %}
      {% if not h.resource_view_is_iframed(resource_view) %}
        {{ h.rendered_resource_view(resource_view, resource, package) }}
      {% else %}
        <div class="data-viewer-error js-hide">
          <p class="text-danger">
            <i class="fa fa-info-circle"></i>
            {{ _('This resource view is not available at the moment.') }}
            <a href="#" data-bs-toggle="collapse" data-bs-target="#data-view-error">
              {{ _('Click here for more information.') }}
            </a>
          </p>
          <p id="data-view-error" class="collapse"></p>
          <p>
            <a href="{{ resource.url }}" class="btn btn-default btn-lg resource-url-analytics" target="_blank" rel="noreferrer">
              <i class="fa fa-lg fa-arrow-circle-down"></i>
              {{ _('Download resource') }}
            </a>
          </p>
        </div>
        {% if not to_preview %}
          {% set current_filters = request.args.get('filters') %}
          {% if current_filters %}
            {% set src = h.url_for(package['type'] ~ '_resource.view', id=package['name'],
              resource_id=resource['id'],
              view_id=resource_view['id'],
              filters=current_filters, qualified=true)  %}
          {% else %}
            {% set src = h.url_for(package['type'] ~ '_resource.view', id=package['name'],
              resource_id=resource['id'],
              view_id=resource_view['id'], qualified=true)  %}
          {% endif %}
        {% else %}
          {# When previewing we need to stick the whole resource_view as a param as there is no other way to pass to information on to the iframe #}
          {% set src = h.url_for(package['type'] ~ '_resource.view', id=package['name'], resource_id=resource['id'], qualified=true) + '?' + h.urlencode({'resource_view': h.dump_json(resource_view)}) %}
        {% endif %}
        <iframe title="Data viewer" src="{{ src }}" frameborder="0" width="100%" data-module="data-viewer">
          <p>{{ _('Your browser does not support iframes.') }}</p>
        </iframe>
      {% endif %}
    </div>
    <div id="embed-{{ resource_view['id'] }}" class="modal fade resource-view-embed">
      <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <h3 class="modal-title">{{ _("Embed resource view") }}</h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ _('Close') }}"></button>

      </div>
      <div class="modal-body">
        <p class="embed-content">{{ _("You can copy and paste the embed code into a CMS or blog software that supports raw HTML") }}</p>
        <div class="row">
          <div class="col-md-6">
            {{ form.input("width", label=_("Width"), value=700, classes=["control-full"]) }}
          </div>
          <div class="col-md-6">
            {{ form.input("height", label=_("Height"), value=400, classes=["control-full"]) }}
          </div>
        </div>
        {{ form.textarea("code", label=_("Code"), value="", classes=["pre"], rows=3) }}
      </div>
      </div>
      </div>
    </div>
  </div>
{% endblock %}

ckanext/charts/templates/package/snippets/view_form.html
{% import 'macros/form.html' as form %}

{% set data = data or {} %}
{% set errors = errors or {} %}

{{ form.errors(error_summary) }}

{% if data.view_type in ["charts_view", "charts_builder_view"] %}
    {% include form_template %}
{% else %}
    {{ form.input('title', id='field-title', label=_('Title'), placeholder=_('eg. My View'), value=data.title, error=errors.title, classes=['control-full', 'control-large'], is_required=true) }}
    {{ form.markdown('description', id='field-description', label=_('Description'), placeholder=_('eg. Information about my view'), value=data.description, error=errors.description) }}

    {% block view_form_filters %}
        {% snippet 'package/snippets/view_form_filters.html', resource=resource, resource_view=resource_view %}
    {% endblock %}

    {# form template is defined in ResouceView extention point #}
    {% if form_template %}
        {% include form_template %}
    {% endif %}
{% endif %}

ckanext/charts/templates/page.html
{% ckan_extends %}

{% block scripts %}
    {{ super() }}

    {% if h.charts_include_htmx_asset() %}
        {% asset "charts/charts-htmx" %}
    {% endif %}
{% endblock scripts %}

ckanext/charts/templates/scheming/form_snippets/chart_checkbox.html
{% set val = data[field.field_name] %}

<div class="form-group">
	<label for="field-{{ field.field_name }}" class="no-dots">
        {# the hidden field requires to properly uncheck the field that is True by default #}
        <input type="hidden" name="{{ field.field_name }}" value="false">
		<input id="field-{{ field.field_name }}"
			type="checkbox"
			name="{{ field.field_name }}"
			value="true"
			{{"checked " if (val is string and 'true' in val) or val }} />
		{{ field.label }}
	</label>

	{%- snippet 'scheming/form_snippets/help_text.html', field=field -%}
</div>

ckanext/charts/templates/scheming/form_snippets/chart_color_picker.html
<div class="form-group control-full control-large">
    <label for="{{ field.field_name }}">{{ field.label }}</label>
    <div class="controls ">
        <input type="color" id="{{ field.field_name }}" name="{{ field.field_name }}" value="{{ data[field.field_name] }}">
    </div>
</div>

ckanext/charts/templates/scheming/form_snippets/chart_engine_details.html
<div class="form-group control-full control-large">
    <div class="controls">
        <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#engineDetailsModal">
            {{ _("Engine Details") }}
        </button>
    </div>
</div>


<div class="modal fade" id="engineDetailsModal" tabindex="-1" role="dialog" aria-labelledby="engineDetailsModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="moreInfoModalLabel">{{ _("Engine Details") }}</h5>
                <button type="button" class="btn-close close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <p>
                    {{ _("The zoom functionality is currently supported for Chart.js and Plotly charts. These libraries offer built-in zoom and pan features, allowing users to interact with the data by zooming in, out, or panning across the chart.") }}
                </p>
                <p>
                    {{ _("Observable Plot does not yet support zoom and pan features as some other charting libraries do. We are actively working to enhance our charting capabilities and may include native support for zoom and pan in Observable Plot in future updates.") }}
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">{{ _("Close") }}</button>
            </div>
        </div>
    </div>
</div>

ckanext/charts/templates/scheming/form_snippets/chart_filter.html
<div
    class="form-group control-full control-large charts-filters"
    data-module="charts-filters"
    data-module-resource-id="{{ resource_id }}"
    data-module-columns="{{ h.charts_get_resource_columns(resource_id) }}">
    <label for="vol">{{ field.label }}</label>
    <div class="controls">
        <div class="filter-container"></div>

        <input class="filters-input" type="hidden" id="{{ 'field-' + field.field_name }}" name="{{ field.field_name }}" value="{{ data[field.field_name] }}">
        <button class="add-filter-btn btn btn-primary" type="button">
            {{ _("Add filter") }}
        </button>
    </div>
</div>

ckanext/charts/templates/scheming/form_snippets/chart_range.html
<div class="form-group control-full control-large">
    <label for="vol">{{ field.label }}</label>
    <div class="controls ">
        <input type="range" id="{{ field.field_name }}" name="{{ field.field_name }}" min="{{ field.min or 0}}" max="{{ field.max or 1}}" step="{{ field.step or 0.1}}" value="{{ data[field.field_name] }}">
    </div>
</div>